//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rDiaDiem : IEntity
    {
        public rDiaDiem()
        {
            this.rKhachHangs = new HashSet<rKhachHang>();
        }
    
        public int Ma { get; set; }
        public int MaNuoc { get; set; }
        public string Tinh { get; set; }
    
        public virtual rNuoc rNuoc { get; set; }
        public virtual ICollection<rKhachHang> rKhachHangs { get; set; }
    
        public int GetKey()
        {
            return Ma;
        }
    }
}
