//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhachHang
    {
        public rKhachHang()
        {
            this.rKhachHangChanhs = new HashSet<rKhachHangChanh>();
            this.tCongNoKhachHangs = new HashSet<tCongNoKhachHang>();
            this.tDonHangs = new HashSet<tDonHang>();
            this.tGiamTruKhachHangs = new HashSet<tGiamTruKhachHang>();
            this.tNhanTienKhachHangs = new HashSet<tNhanTienKhachHang>();
            this.tPhuThuKhachHangs = new HashSet<tPhuThuKhachHang>();
            this.tToaHangs = new HashSet<tToaHang>();
        }
    
        public int Ma { get; set; }
        public int MaDiaDiem { get; set; }
        public string TenKhachHang { get; set; }
        public bool KhachRieng { get; set; }
    
        public virtual rDiaDiem rDiaDiem { get; set; }
        public virtual ICollection<rKhachHangChanh> rKhachHangChanhs { get; set; }
        public virtual ICollection<tCongNoKhachHang> tCongNoKhachHangs { get; set; }
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
        public virtual ICollection<tGiamTruKhachHang> tGiamTruKhachHangs { get; set; }
        public virtual ICollection<tNhanTienKhachHang> tNhanTienKhachHangs { get; set; }
        public virtual ICollection<tPhuThuKhachHang> tPhuThuKhachHangs { get; set; }
        public virtual ICollection<tToaHang> tToaHangs { get; set; }
    }
}
