//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhachHangChanh : IEntity
    {
        public int Ma { get; set; }
        public int MaChanh { get; set; }
        public int MaKhachHang { get; set; }
        public bool LaMacDinh { get; set; }
    
        public virtual rChanh rChanh { get; set; }
        public virtual rKhachHang rKhachHang { get; set; }
    
        public int GetKey()
        {
            return Ma;
        }
    }
}
