//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhoHang : IEntity
    {
        public rKhoHang()
        {
            this.rCanhBaoTonKhoes = new HashSet<rCanhBaoTonKho>();
            this.tChuyenKhoes = new HashSet<tChuyenKho>();
            this.tChuyenKhoes1 = new HashSet<tChuyenKho>();
            this.tDonHangs = new HashSet<tDonHang>();
            this.tNhapHangs = new HashSet<tNhapHang>();
            this.tTonKhoes = new HashSet<tTonKho>();
        }
    
        public int Ma { get; set; }
        public string TenKho { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual ICollection<rCanhBaoTonKho> rCanhBaoTonKhoes { get; set; }
        public virtual ICollection<tChuyenKho> tChuyenKhoes { get; set; }
        public virtual ICollection<tChuyenKho> tChuyenKhoes1 { get; set; }
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
        public virtual ICollection<tNhapHang> tNhapHangs { get; set; }
        public virtual ICollection<tTonKho> tTonKhoes { get; set; }
    
        public int GetKey()
        {
            return Ma;
        }
    }
}
