//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rLoaiNguyenLieu : IEntity
    {
        public rLoaiNguyenLieu()
        {
            this.rNguyenLieux = new HashSet<rNguyenLieu>();
        }
    
        public int Ma { get; set; }
        public string TenLoai { get; set; }
    
        public virtual ICollection<rNguyenLieu> rNguyenLieux { get; set; }
    
        public int GetKey()
        {
            return Ma;
        }
    }
}
