//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rNguyenLieu
    {
        public rNguyenLieu()
        {
            this.rMatHangNguyenLieux = new HashSet<rMatHangNguyenLieu>();
            this.tNhapNguyenLieux = new HashSet<tNhapNguyenLieu>();
        }
    
        public int Ma { get; set; }
        public int MaLoaiNguyenLieu { get; set; }
        public int DuongKinh { get; set; }
    
        public virtual rLoaiNguyenLieu rLoaiNguyenLieu { get; set; }
        public virtual ICollection<rMatHangNguyenLieu> rMatHangNguyenLieux { get; set; }
        public virtual ICollection<tNhapNguyenLieu> tNhapNguyenLieux { get; set; }
    }
}
