//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rNhanVien
    {
        public rNhanVien()
        {
            this.tChiPhis = new HashSet<tChiPhi>();
            this.tChuyenHangs = new HashSet<tChuyenHang>();
            this.tChuyenKhoes = new HashSet<tChuyenKho>();
            this.tNhapHangs = new HashSet<tNhapHang>();
        }
    
        public int Ma { get; set; }
        public int MaPhuongTien { get; set; }
        public string TenNhanVien { get; set; }
    
        public virtual rPhuongTien rPhuongTien { get; set; }
        public virtual ICollection<tChiPhi> tChiPhis { get; set; }
        public virtual ICollection<tChuyenHang> tChuyenHangs { get; set; }
        public virtual ICollection<tChuyenKho> tChuyenKhoes { get; set; }
        public virtual ICollection<tNhapHang> tNhapHangs { get; set; }
    }
}
