//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rPhuongTien
    {
        public rPhuongTien()
        {
            this.rNhanViens = new HashSet<rNhanVien>();
        }
    
        public int Ma { get; set; }
        public string TenPhuongTien { get; set; }
    
        public virtual ICollection<rNhanVien> rNhanViens { get; set; }
    }
}
