//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiPhi
    {
        public int Ma { get; set; }
        public int MaNhanVienGiaoHang { get; set; }
        public int MaLoaiChiPhi { get; set; }
        public int SoTien { get; set; }
        public System.DateTime Ngay { get; set; }
        public string GhiChu { get; set; }
    
        public virtual rLoaiChiPhi rLoaiChiPhi { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
    }
}
