//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChuyenKho
    {
        public tChuyenKho()
        {
            this.tChiTietChuyenKhoes = new HashSet<tChiTietChuyenKho>();
        }
    
        public int Ma { get; set; }
        public int MaNhanVien { get; set; }
        public int MaKhoHangXuat { get; set; }
        public int MaKhoHangNhap { get; set; }
        public System.DateTime Ngay { get; set; }
    
        public virtual rKhoHang rKhoHang { get; set; }
        public virtual rKhoHang rKhoHang1 { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
        public virtual ICollection<tChiTietChuyenKho> tChiTietChuyenKhoes { get; set; }
    }
}
