//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMatHang : IEntity
    {
        public tMatHang()
        {
            this.rCanhBaoTonKhoes = new HashSet<rCanhBaoTonKho>();
            this.rMatHangNguyenLieux = new HashSet<rMatHangNguyenLieu>();
            this.tChiTietChuyenKhoes = new HashSet<tChiTietChuyenKho>();
            this.tChiTietDonHangs = new HashSet<tChiTietDonHang>();
            this.tChiTietNhapHangs = new HashSet<tChiTietNhapHang>();
            this.tTonKhoes = new HashSet<tTonKho>();
        }
    
        public int Ma { get; set; }
        public int MaLoai { get; set; }
        public string TenMatHang { get; set; }
        public int SoKy { get; set; }
        public int SoMet { get; set; }
        public string TenMatHangDayDu { get; set; }
        public string TenMatHangIn { get; set; }
    
        public virtual ICollection<rCanhBaoTonKho> rCanhBaoTonKhoes { get; set; }
        public virtual rLoaiHang rLoaiHang { get; set; }
        public virtual ICollection<rMatHangNguyenLieu> rMatHangNguyenLieux { get; set; }
        public virtual ICollection<tChiTietChuyenKho> tChiTietChuyenKhoes { get; set; }
        public virtual ICollection<tChiTietDonHang> tChiTietDonHangs { get; set; }
        public virtual ICollection<tChiTietNhapHang> tChiTietNhapHangs { get; set; }
        public virtual ICollection<tTonKho> tTonKhoes { get; set; }
    
        public int GetKey()
        {
            return Ma;
        }
    }
}
