//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNhapHang
    {
        public tNhapHang()
        {
            this.tChiTietNhapHangs = new HashSet<tChiTietNhapHang>();
        }
    
        public int Ma { get; set; }
        public int MaNhanVien { get; set; }
        public int MaKhoHang { get; set; }
        public int MaNhaCungCap { get; set; }
        public System.DateTime Ngay { get; set; }
    
        public virtual rKhoHang rKhoHang { get; set; }
        public virtual rNhaCungCap rNhaCungCap { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
        public virtual ICollection<tChiTietNhapHang> tChiTietNhapHangs { get; set; }
    }
}
